version: '3'

services:
  devfaq_db:
    image: postgres:11-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'database_development'
      POSTGRES_PASSWORD: 'api2022'
